const BG = {
    header: [
        'Начална страница',
        'Предпочитан език',
        'За компанията',
        'Контакти',
        'Записване',
        'Нидерландия',
        'Услуги',
        'Информация',
        'Екип',
        'Нашите Услуги',
        'Препоръки',
    ],
    footer: [
        'Всички права са собственост на компанията @ Domakin ',
        'Условия & Регулации',
        'Нидерландия',
        'За компанията',
        "Информация",
        'Екип',
        'Услуги',
        'Oгледи',
        'Очаквайте още скоро...',
        'Помощ',
        'Контакти',
        'Наемане',
        'Отдаване',
        'Отзиви и Дарения',
        'Препоръки'
    ],
    about: [
        "Информация за нас",
        "За компанията",
        'Подпомагане при търсене на жилище',
        'Кога да ни потърсите:',
        'В края на 2022 година част от екипа на Domakin.nl създаде студентската организация с нестопанска цел',
        'с идеята да се подобри животът на българските студенти в Холандия. Част от тази ни наша мисия е свързана и с едно от най-големите предизвикателства на студентите в Холандия, а именно намирането на жилище. Затова ние създадохме Domakin.nl с цел да улесним този процес и да помогнем на повече българи да намерят своя нов дом.',
        'Едно от най-големите премеждия на всеки студент в Нидерландия е намиране на жилище в първата учебна година, а и през следващите. Екипът на Domakin.nl ще Ви помогне: ',
        'Ако сте в България и искате да намерите жилище, но няма как да присъствате на огледи, ние сме тук вместо Вас!',
        'Ако искате да намерите жилище, нашият сайт ще Ви помогне!',
        'Ако си търсите съквартирант или искате да си прехвърлите стария договор на някого, нашият сайт е тук за Вас!',
    ],
    contact: [
        'Свържете се с нас',
        'Контакти',
        'E-поща',
        'Телефон за връзка',
        'Очаквайте скоро',
        'Офис Адрес',
        'Очаквайте скоро',
        'Съобщението е изпратено успешно!',
        'Грешка! Моля опитайте пак!',
        'Свържете се директно с нас',
        'Въведете вашия имейл',
        'Въведете тема на запитване',
        'Въведете вашето запитване',
        'Изпрати запитване'
    ],
    viewing: [
        'Извършване на огледи',
        'Огледи',
        'Ние извършваме огледа вместо Вас',
        'Намерили сте квартира, но нямате възможност да присъствате на оглед или сте в процес на търсене и искате да си осигурите агент за огледи.',
        'Предлагаме услугата агент за огледи, при която ние отиваме на оглед от Ваше име. При желание документираме целия оглед и задаваме въпросите Ви лично на наемодателя. Ако има възможност, можем да направим и видео връзка в реално време, за да се доближим максимално до присъствен оглед. Свържете се с нас, следвайки стъпките по-долу:',
        '1) Попълнете бланката по-долу',
        '2) Изчакайте връзка с наш агент',
        '3) Заедно планирайте оглед/ите и оставете всичко останало на нас',
        'Попълнете информацията си',
        'Име',
        'Фамилия',
        'Телефон за връзка (+ кода на държавата)',
        'Ел. поща',
        'Допълнителна информация, която искате да предадете на агента ни',
        'Давам разрешение компанията да се свърже с мен по телефон или по ел. поща, като разрешавам подадената лична информация да бъде запазена и използване единствено във връзка с предлаганата услуга',
        'Изпращане',
        {
            errors: [
                "Моля, въведете име",
                "Моля, въведете фамилия",
                'Номерът е непълен или не започва с държавен индекс (например +359)',
                "Моля, въведете телефонен номер",
                "Имейлът е навалиден",
                "Моля, въведете имейл",
                "Условията трябва да бъдат приети",
                'Моля посочете град на огледа',
                'Моля посочете дата на огледа',
                'Моля посочете време на огледа'
            ]
        },
        'Успешно свързване',
        'Вашата информация вече е получена и очаква разглеждане от наш агент! Благодарим Ви за доверието - очаквайте връзка!',
        'Град на огледа',
        'Дата:',
        'Час:',
        'Адрес на огледа (препоръчително поле)',
    ],
    renting: [
        'Наемане на квартира',
        'Наемане',
        'Намерете подходящата квартира за вас',
        'Нашият сайт предлага различни квартири спрямо различни условия. Разгледайте списъка с различни имоти и кликнете снимката, за да разгледате галерията. При интерес, следвайте стъпките: ',
        `1) Изберете имот от секцията по-долу и кликнете 'Избери'`,
        '2) Попълнете формата, която ще се появи при селектиран имот',
        '3) Изчакайте връзка с наш агент за допълнителна информация за имота',
        '4) Завършете сделката с нашия агент',
        'Услуги',
        'Предлагани имоти',
        'на месец',
        'избери',
        "В момента нямаме налични имоти - моля проверявайте сайта редовно или се свържете с нас!"
    ],
    lending: [
        'Прехвърли стар договор',
        'Прехвърляне',
        'Прехвърлете стария си договор чрез нас',
        'Предлагаме опцията да си прехвълите оставащия договора на намерен от нас клиент. За тази цел, Вашият договор трябва да позволява прехвърляне и съгласие на наемодателя. За да стартирате процедурата, моля изпълнете следни стъпки: ',
        '1) Попълнете бланката по-долу',
        '2) Изчакайте обратна връзка с наш агент',
        '3) Заедно разгледайте договора Ви и завършете сделката',
    ],

    emergency_housing: [
        'Спешно настаняване',
        'Ако търсите място за престой до намиране на собствено жилище',
        'Намерете място за кратък престой в едно от нашите надеждни имоти, предоставени от доверени хора. Цената е ниска (ако има такава), а престоят е ограничен, но може да помогне на някого, който се нуждае. Ако имате нужда от спешно настаняване в Нидерландия, просто следвайте стъпките по-долу:',
        ` 1) Изберете опцията 'Търсене' по-долу`,
        '2) Изберете стая, като щракнете върху бутона за избор',
        '3) Попълнете данните си във формата, който ще се появи',
        '4) Изчакайте отговор от наша страна, за да получите информация за собственика на имота',
        'Ако предоставяте място за кратко време',
        'Предоставете легло/диван на някого, който се нуждае от кратък престой. Много хора, по-специално студенти, пристигат в Нидерландия без място за живеене, за да не пропуснат учебата си. Можете значително да помогнете, като предложите спешно настаняване на студент до техното настаняване с нашата помощ. За да въведете своя имот в списъка, просто следвайте тези стъпки:',
        `1) Изберете опцията 'Предлагане' по-долу`,
        `3) Попълнете своите данни и данните за имота във формата, който ще се появи`,
        '4) Изчакайте отговор от наша страна, за да бъдете одобрени',
        "Екипът на Домакин е истински благодарен на всички, които са готови да помогнат",
        '...',
        'Търсене',
        'Предлагане',
        'Лична информация',
        'Име',
        'Фамилия',
        'Телефон (+ и код на държавата)',
        'Имейл',
        'Кратко се представете',
        'Информация за имота',
        'Местоположение',
        'Максимален период на престоя',
        'Цена за нощувка',
        'Можете го предоставите безплатно',
        'Описание на имота (например дали е легло/диван и какво друго може да използва наемателят)',
        'Давам съгласието си да бъда свързван от организацията за целите на услугата',
        'Снимки на стаята',
        ' Предайте поне 3 снимки и не повече от 6',
        '* Допълнителни снимки няма да бъдат приети',
        '* Поддържани формати са jpg, jpeg и png',
        'изпрати стая',
        `* Не забравяйте снимките`,
        {
            errors: [
                'името е задължително',
                'фамилията е задължителна',
                'имейлът е задължителен',
                'телефонът е твърде кратък',
                'невалиден телефон (моля, добавете + и код на държавата)',
                'телефонът е задължителен',
                'необходимо е вашето описание',
                'местоположението е задължително',
                'периодът е задължителен',
                'цената е задължителна',
                'описанието на имота е задължително',
                'Трябва да се приемат условията',
                'Има невалиден файл'
            ]
        },
        'Търсене',
        'Предлагане'
    ],
    FOR_RENT: [
        {
            id: '3',
            status: 'Свободна',
            price: '~' + 1050,
            free: true,
            type: 'Единична Стая',
            location: 'Tweede Oosterparkstraat 3, Amsterdam',
            description: ['Реновирана стая в апартамент с две спални. Кухнята и холът са напълно обзаведени. Спалнята е наполовина обзаведена, като леглото и гардеробът могат да бъдат или закупени от предния наемодател, или премахнати, секцията остава в стаята. Другият съквартирант е работещ мъж на 26 години. Търси се съквартирант със сходен профил.', 'Наемът включва сметки (вода, ток, интернет и т.н.).', 'Свободна от 8 септември 2023 до юни 2024 с опция за удължаване.'],
            main_image: "assets/img/properties/property_3/(1).jpg",
            images: ['assets/img/properties/property_3/(2).jpg', 'assets/img/properties/property_3/(3).jpg', 'assets/img/properties/property_3/(4).jpg', 'assets/img/properties/property_3/(5).jpg', 'assets/img/properties/property_3/(6).jpg', 'assets/img/properties/property_3/(7).jpg', 'assets/img/properties/property_3/(8).jpg', 'assets/img/properties/property_3/(9).jpg', 'assets/img/properties/property_3/(10).jpg'],
        },
        {
            id: '2',
            status: 'Заета',
            price: 784,
            free: false,
            type: 'Студио',
            location: 'Hoogeweg 1, Groningen',
            description: ['Студио от септември до февруари, 784 евро на месец, всичко включено.', 'Алина отива на обмен до февруари и си търси някой да й вземе студиото.', 'На този адрес регистрация не е възможна, така че това студио не е подходящо за студенти първа година, които не са регистрирани в Холандия.'],
            main_image: "assets/img/properties/studio/1.jpg",
            images: ['assets/img/properties/studio/2.jpg', 'assets/img/properties/studio/3.jpg', 'assets/img/properties/studio/4.jpg', 'assets/img/properties/studio/5.jpg', 'assets/img/properties/studio/6.jpg', 'assets/img/properties/studio/7.jpg'],
        },
        {
            id: '0',
            status: 'Заета',
            price: 600,
            free: false,
            type: 'Стая за двама',
            location: 'Visvliet, Netherlands',
            description: ['Стая за двама в споделена къща на 20 км от Гроьнинген. Къщата се държи от възрастна португалска двойка. В цената са включени всички консумативи', 'Споделя се хол, баня и тоалетна', 'Договорът е за 12 месеца', 'Налична от 1ви август'],
            main_image: "assets/img/properties/1.jpg",
            images: ['assets/img/properties/21.jpg', 'assets/img/properties/18.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/4.jpg', 'assets/img/properties/5.jpg', 'assets/img/properties/6.jpg', 'assets/img/properties/8.jpg', 'assets/img/properties/9.jpg', 'assets/img/properties/10.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },
        {
            id: '1',
            status: 'Заета',
            price: 400,
            free: false,
            type: 'Единична стая',
            location: 'Visvliet, Netherlands',
            description: ['Единична стая в споделена къща на 20 км от Грьонинген. Къщата се държи от възрастна португалска двойка. В цената са включени всички консумативи.', 'Споделя се хол, баня и тоалетна', 'Договорът е за 12 месеца', 'Налична от 1ви август'],
            main_image: "assets/img/properties/7.jpg",
            images: ['assets/img/properties/19.jpg', 'assets/img/properties/20.jpg', 'assets/img/properties/2.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },
    ],
    home: [
        'Компания за подпомагане на намиране на квартири',
        'Намерете Вашето място',
        'с наша помощ',
        'Ние ще Ви помогнем с намиране и отдаване на квартири във всяка част на Холандия',
        'Направете запитване',
    ],
    features: [
        'Услуги',
        'Нашите услуги',
        'Извършване на огледи',
        'Нашите агенти извършват огледите вместо Вас, като спазват всички Ваши изисквания',
        'Към услугата',
        'Наемане на квартира',
        'Разгледайте нашите предложения в околността и се свържете с нас, за да получите повече информация',
        'Отдай стая',
        'Услуги',
        'Ако искаш да намериш съквартирант или да предадеш стаята си на нов наемател, който да заеме стаята ти',
        'Извънредно настаняване',
        'Ако търсиш или предлагаш кратък престой за студент в нужда'
    ],
    team: [
        'Екип',
        'Екип',
        {
            name: 'Лазар Попов',
            position: 'Агент за огледи',
            about: '26, бакалавър по изкуствен интелект',
            aboutExtra: `Здравейте, казвам се Лазар, от Русе, но живея в Грьонинген вече пета година. Аз съм магистър по специалност “Изкуствен интелект”. Познавам града добре и съм запознат с търсенето и намирането на жилища под наем. Моите интереси са бойни спортове и изкуствен интелект, като освен агент в Domakin.nl съм президент и съосновател на студентската non-profit организация Bulgarian Society Groningen. Ще се радвам да Ви бъда от помощ!`
        },
        {
            name: 'Сава Попов',
            position: 'Агент за огледи',
            about: '20,  студент по креативна медиа',
            aboutExtra: 'Здравейте, аз съм Сава и съм студент в специалност “Креативна медиа и технологии” в Грьонинген. Прекарвах голяма част от свободното си време в търсене на апартамент, ходене по огледи и разпитвайки познати. След многобройни неуспешни опити успях да намеря жилище и смятам, че вече добре осъзнавам грешките и успехите си при търсенето на квартири. Ще се радвам да бъда от полза на всеки, изпаднал в моята ситуация!'
        },
        {
            name: 'Константин Сонев',
            position: 'Агент за огледи',
            about: '21,  студент по креативна медиа',
            aboutExtra: `Здравейте, казвам се Константин и уча  специалност “Креативна медиа и технологии” в Грьонинген. В края на миналата учебна година ми се наложи да си търся нова квартира. Беше изключително трудно да се сдобия със стая в града и бях удовлетворен, когато намерих място след многократни, неуспешни опити. Има много затруднения при намирането на квартири заради огромния поток от студенти и високи наеми. Знаем, че много от вас имат желанието да учат в града и срещат същите затруднения, най-вече когато не са в града. Поради тази причина ние от Domakin.nl искаме да помогнем, предоставяйки нашите услуги. Очаквам да работим заедно!`
        },
        {
            name: 'Димитър Стаматов',
            position: 'Агент за огледи',
            about: '22, студент по международен бизнес',
            aboutExtra: 'Здравейте, казвам се Димитър Стаматов, на 22 години и съм студент трета година в Холандия. Уча бизнес и работя като барман, а в свободното си време тренирам бойни спортове и се занимавам с музика. Като всеки студент в Холандия знам колко е трудно намирането на жилище особено през първата година и затова бих се радвал да улесня всеки бъдещ студент с работата ми като агент в Domakin.nl.'
        },
        {
            name: 'Владислав Маринов',
            position: 'IT Мениджър',
            about: '22, International Business student',
            aboutExtra: 'Здравейте, казвам се Владислав и съм студент по бизнес в Лондон, Англия. Макар и в друга държава, аз също съм запознат с проблемите, които един студент може да срещне с търсенето на жилище. Стрес, отчаяние и ярост са само няколко емоции, които лично аз съм изпитвал при търсенето на квартира в Лондон и знам какви трудности може да изпита човек, особено когато търси дистанционно. За мен е удоволствие да работя по тази платформа, която вярвам, че ще помогне на мнозина!'
        },
        {
            name: 'Радост Лозанова',
            position: 'Дизайн Мениджър',
            about: '22, International Business student',
            aboutExtra: `Здравейте! Аз съм Радост, креативен директор и съосновател на Bulgarian Society Groningen. Като студентка съм живяла в доста държави, което е съпроводено с често местене. Като част от екипа на Domakin.nl, ще се радвам да помогна на повече българи да намерят своя нов дом в Холандия.`
        },
        'Агенти',
        'Маркетинг',
        'Дизайн',
    ],
    error: [
        'Внимание, попаднахте на грешка!',
        'Страницата не е намерена',
        'Страницата, която търсехте, не съществува! Възможно е да е преместена или изтрита.',
        ' Обратно към начало',
    ],
    feedbacks: [
        'Остави отзив',
        'За нас',
        'Отзиви и дарения',
        'Сподели Вашето впечатление от услугите ни',
        'Име',
        'Вашият отзив',
        'Минимум 20 символа',
        'Изпрати',
        'Името е задължително',
        'Не оставяйте отзива празен',
        'Минимум 20 символа са нужни',
        'Надвишихте лимита от 300 думи',
        'Благодарим, очаквайте отзивът ви да бъде одобрен съвсем скоро!',
        'Отзиви',
        'Дарения',
        'Искате да помогнете на организацията?',
        'Вече приемаме и дарения - чрез тях и чрез вашите отзиви, ние от Домакин успяваме да подпомагаме повече и повече студенти!',
        'Помогни'
    ],
    recommendations: [
        'Нашите препоръки',
        'Помощи',
        'Към нашите услуги',
        'Препоръчно от Domakin.nl',
        'Екипът на Domakin поддържа списък със сайтове и групи за търсене и отдаване на квартири в Грьонинген. Тук може да намерите най-използваните платформи, като ние допълнително можем да Ви помогнем с търсенето или предлагането на квартира! Просто кликнете заглавието, за да видите платформата.',
        'Уебстраници',
        'от Domakin.nl',
        'При нужда от информация или допълнителна помощ, моля свържете се с нас чрез страницата за контакти или страницата с услуги!',
        'Бъдете нащрек за фалшиви оферти! Проверявайте фейсбук профила на предлагащия, изисквайте оглед и се уверете, че офертата е легитимна, преди да изпратите документи и да правите плащания! Свържете се с нас при нужда от асистенция!'
    ]
}

const EN = {
    header: [
        'Home',
        'Change language',
        'About',
        'Contact',
        'Register',
        'The Netherlands',
        'Services',
        'Information',
        'Agents',
        'Our Services',
        'Recommendations'
    ],
    footer: [
        'All Rights Reserved @ Domakin ',
        'Terms & Policy',
        'The Netherlands',
        'Company',
        "About us",
        'Team',
        'Services',
        'Viewings',
        'Expect more soon...',
        'Support',
        'Contact us',
        'Renting',
        'Lending',
        'Feedbacks & Donations',
        'Recommendations'
    ],
    about: [
        "About the company",
        "About us",
        'Helping you find a place',
        'When to reach us:',
        'At the end of 2022 some of the founders of Domakin started the NPO',
        'with the aim to help the Bulgarian students of Groningen. Part of our mission includes one of the biggest challenges of students in Groningen - finding an accommodation. That is why we created Domakin in order to make this process easier for many that find difficulties in finding a place to live.',
        'It is hard for a student to find a place to live in their first year and even in the rest. The team of Domakin will help you with: ',
        'If you are located in Bulgaria and want to find a place but you are unable to make the viewing, we are here for you!',
        'If you want to find a place, we are here for you!',
        'If you are searching for a new flatmate or want to transfer your contract to someone else, we are here for you!',
    ],
    contact: [
        'Contact us',
        'Contact',
        'E-mail',
        'Telephone',
        'Expect soon',
        'Office Address',
        'Expect soon',
        'Your message was sent successfully',
        'Error! Please try again!',
        'Contact us directly',
        'Enter your email',
        'Enter the subject',
        'Enter you message',
        'Send'
    ],
    viewing: [
        'Viewing service',
        'Viewing',
        'Let us make the viewing for you',
        'You have found a room/apartment but you are unable to attend the viewing or you are in the process of searching and want to ensure that someone can represent you for the viewing.',
        'We offer agents for viewings where we go to the viewing instead of you. By your request we document the whole process and make any inqueries to the landlord. If there is a possibility, we can make a live connection with you so you can realisticaly experience the viewing. Contact us by following the steps below: ',
        '1) Fill your details in the form',
        '2) Wait for one of our agents to contact you',
        '3) Arrange the viewing/s and leave the rest to us',
        'Fill your details',
        'Name',
        'Surname',
        'Phone to be contacted (+ and country code)',
        'Email',
        'Any comments you would like to be sent to our agent',
        'I give my consent to be contacted by the company via phone or email and for them to store my information for service purposes only',
        'Submit Request',
        {
            errors: [
                "Name is required",
                "Surname is required",
                'Phone number is not full or does not start with country code (example +359)',
                "Phone is required",
                "Please enter a valid email",
                "Please enter an email",
                "Terms must be accepted",
                'Please provide the city of the viewing',
                'Please provide the date of the viewing',
                'Please provide the time of the viewing'
            ]
        },
        'Successful Request',
        'Your information has been sent so expect soon to be contacted by one of our agents! Thank you again for the trust and see you soon!',
        'City of viewing',
        'Date:',
        'Time:',
        'Address of viewing (optional)',
    ],
    renting: [
        'Renting accommodations',
        'Renting',
        'Find the perfect place for you',
        'Our platform contains different properties.',
        `1) Choose a property from the list below and click 'Select'`,
        '2) Fill the form that will appear once a property has been selected',
        '3) Wait to be contacted by our agent to finilize the deal',
        '4) Finish the deal with our agent',
        'Services',
        'Properties',
        'per month',
        'select',
        "No properties at the moment - please check again later!"
    ],
    lending: [
        'Transfer and old contract',
        'Transfering',
        'Transfer your old contract through us',
        'We offer you to transfer the remain of your contract to one of our clients. In order to achieve this, your contract should allow for such execution and your landlord should be informed. To start, simply follow the steps below: ',
        '1) Fill the form',
        '2) Wait for our agent to contact you',
        '3) Together check the contract and finilize the service',
    ],
    emergency_housing: [
        'Emergency Housing',
        'If you are looking for a place to stay until finding your own',
        'Find a place for a short stay in one of our trusted properties lent by trusted people. The cost is low (if any) and the stay is limited but can help someone in need. If you need emergency housing in the Netherlands, simply follow the steps:',
        `1) Select the 'Searching' option below`,
        '2) Choose a room by clicking select',
        '3) Fill your details in the form that will appear',
        '4) Wait for a response from our side to receive the information about the owner of the property',
        'If you are giving a place for a short time',
        'Lend an extra bed/coach to someone in need for a short stay. Many people, and more specifically students, come to the Netherlands without a place to live in order not to miss out on their studies. You can significantly help by offering to urgently house a student until they find their accommodation with our help. To list your property, simply follow these steps:',
        `1) Select the 'Offering' option below`,
        `3) Fill your details and the property's in the form that will appear`,
        '4) Wait for a response from our side to approve you',
        `"The team of Domakin is genuinely thankful to all who are willing to help"`,
        '...',
        'Searching',
        'Offering',
        'Personal information',
        'Name',
        'Surname',
        'Phone (+ and country code)',
        'Email',
        'Briefly describe yourself',
        'Property inforamtion',
        'Location',
        'Maximum staying period',
        'Price per night',
        '*You can also lend it out of charge',
        'Description of property (such as is it a bed/coach/etc., what else can the tenent use)',
        'I give my permission to be contacted by the organization for the purposes of the service',
        'Room pictures',
        '* Submit at least 3 images and no more than 6',
        '* Extra images will not be received',
        '* Supported formats are jpg, jpeg and png',
        'send room',
        `* Don't forget images`,
        {
            errors: [
                'name is required',
                'surname is required',
                'email is required',
                'phone is too short',
                'invalid phone (please add the + and country code)',
                'phone is required',
                'your description is required',
                'location is required',
                'period is required',
                'price is required',
                'the property description is required',
                'Terms must be accepted',
                'There is an invalid file'
            ]
        },
        'Searching',
        'Offering'
    ],
    FOR_RENT: [
        {
            id: '3',
            status: 'Available',
            price: '~' + 1050,
            free: true,
            type: 'Single Room',
            location: 'Tweede Oosterparkstraat 3, Amsterdam',
            description: ['A small but nice room in a two bedroom apartment. Living room, kitchen, bathroom have everything included. The room comes semi-furnished, the bed and the clothing rack can be bought from the previous tenant or removed. The shelf stays. There is one more working male tenant - 26 years old.', 'Rent includes service cost, bills, wifi, el, gas, water', '8th of September 2023 - June 2024 with a possibility of extension'],
            main_image: "assets/img/properties/property_3/(1).jpg",
            images: ['assets/img/properties/property_3/(2).jpg', 'assets/img/properties/property_3/(3).jpg', 'assets/img/properties/property_3/(4).jpg', 'assets/img/properties/property_3/(5).jpg', 'assets/img/properties/property_3/(6).jpg', 'assets/img/properties/property_3/(7).jpg', 'assets/img/properties/property_3/(8).jpg', 'assets/img/properties/property_3/(9).jpg', 'assets/img/properties/property_3/(10).jpg'],
        },
        {
            id: '2',
            status: 'Taken',
            price: 784,
            free: false,
            type: 'Studio',
            location: 'Hoogeweg 1, Groningen',
            description: ['Studio from September to February, , 784 euro per month, all bills included', 'Alina is going on an exchange program and would like somebody to take her studio', 'As registration of living is not possible at the place, it is NOT suitable for first year students who have not yet been registered'],
            main_image: "assets/img/properties/studio/1.jpg",
            images: ['assets/img/properties/studio/2.jpg', 'assets/img/properties/studio/3.jpg', 'assets/img/properties/studio/4.jpg', 'assets/img/properties/studio/5.jpg', 'assets/img/properties/studio/6.jpg', 'assets/img/properties/studio/7.jpg'],
        },
        {
            id: '0',
            status: 'Taken',
            free: false,
            price: 600,
            type: 'Double Room',
            location: 'Visvliet, Netherlands',
            description: ['Room for two in a shared house just 20km from Groningen. The house is owned by a Portuguese couple. Price includes all bills', 'Contract is for 12 months', 'Available from 1st of August'],
            main_image: "assets/img/properties/1.jpg",
            images: ['assets/img/properties/21.jpg', 'assets/img/properties/18.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/4.jpg', 'assets/img/properties/5.jpg', 'assets/img/properties/6.jpg', 'assets/img/properties/8.jpg', 'assets/img/properties/9.jpg', 'assets/img/properties/10.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },
        {
            id: '1',
            status: 'Taken',
            free: false,
            price: 400,
            type: 'Single Room',
            location: 'Visvliet, Netherlands',
            description: ['Room for one in a shared house just 20km from Groningen. The house is owned by a Portuguese couple. Price includes all bills', 'Contract is for 12 months', 'Available from 1st of August'],
            main_image: "assets/img/properties/7.jpg",
            images: ['assets/img/properties/19.jpg', 'assets/img/properties/20.jpg', 'assets/img/properties/2.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },

    ],
    home: [
        'Company for accommodation searching',
        'Find your place to live',
        'with our help',
        'Our young team will help you find a place to live in any part of the Netherlands',
        'Contact us',
    ],
    features: [
        'Our Main Focus',
        'Our Services',
        'Viewings',
        `Our agents make the apartment visits for you by also following any client's requirements`,
        'Check it out',
        'Rent an apartment',
        'Check the properties on our site and make an inquery for more information',
        'List a room',
        'Services',
        'Search for a new flatmate / Transfer your contract'
    ],
    team: [
        'Team',
        'Propert Agents',
        {
            name: 'Lazar Popov',
            position: 'Viewing Agent',
            about: '26, Bachelor in Artificial Intelligence',
            aboutExtra: `Hello, my name is Lazar. I'm from Ruse, but I have been living in Groningen for five years now. I have a master's degree in "Artificial Intelligence". I am familiar with the city and have experience in searching for and finding rental properties. My interests include combat sports and artificial intelligence. Besides being an agent at Domakin.nl, I am also the president and co-founder of the non-profit student organization Bulgarian Society Groningen. I would be happy to assist you!`
        },
        {
            name: 'Sava Popov',
            position: 'Viewing Agent',
            about: '20, Creative Media student',
            aboutExtra: `Hello, I'm Sava and I'm a student in the "Creative Media and Technologies" program in Groningen. I have spent a lot of my summer time before coming to this town in searching for apartments, going on viewings, and asking acquaintances for advice. After numerous unsuccessful attempts, I finally managed to find a place, and I believe I now have a good understanding of the mistakes and successes in apartment hunting. I would be glad to help anyone who is in a similar situation!`
        },
        {
            name: 'Konstantin Sonev',
            position: 'Viewing Agent',
            about: '21, Creative Media student',
            aboutExtra: `Hello, my name is Konstantin, and I study "Creative Media and Technologies" in Groningen. At the end of the previous academic year, I had to search for a new apartment. It was extremely difficult to find a room in the city, and I was satisfied when I finally found a place after multiple unsuccessful attempts. There are many difficulties in finding apartments due to the high influx of students and high rents. We know that many of you have the desire to study in the city and face the same difficulties, especially when you are not in the city. That's why we at Domakin.nl want to help by providing our services. I look forward to working together!`
        },
        {
            name: 'Dimitar Stamatov',
            position: 'Viewing Agent',
            about: '22, International Business student',
            aboutExtra: `Hello, my name is Dimitar Stamatov, I'm 22 years old, and I'm a third-year student in the Netherlands. I study business and work as a bartender, and in my free time, I train in combat sports and engage in music. Like every student in the Netherlands, I know how difficult it is to find accommodation, especially in the first year. That's why I would be happy to assist any future student with my work as an agent at Domakin.nl.`
        },
        {
            name: 'Vladislav Marinov',
            position: 'IT Manager',
            about: '22, International Business student',
            aboutExtra: ` Hello, my name is Vladislav, and I'm a business student in London, England. Although in a different country, I am also familiar with the problems a student can encounter when searching for accommodation. Stress, despair, and anger are just a few emotions I have experienced personally while looking for an apartment in London, and I know the difficulties one can face, especially when searching remotely. It is a pleasure for me to work on this platform, which I believe will help many people!`
        },
        {
            name: 'Radost Lozanova',
            position: 'Design Manager',
            about: '22, International Business student',
            aboutExtra: `Hello! I'm Radost, a creative director and co-founder of Bulgarian Society Groningen. As a student, I have lived in several countries, which involved frequent moving. As part of the Domakin.nl team, I would be happy to help more Bulgarians find their new home in the Netherlands.`
        },
        'Agents',
        'Marketing',
        'Design',
    ],
    error: [
        'Be careful - You just got an error!',
        'Page not found',
        'The page you are looking for does not exists',
        ' Back to home',
    ],
    feedbacks: [
        'Leave a feedback',
        'About',
        'Feedbacks & Donations',
        'Share your experience for others to see',
        'Name',
        'Your Feedback',
        'Minimum 20 characters',
        'Send',
        'Name is required',
        'Do not leave empty',
        'Please type at least 20 characters',
        'You passed the 300 characters limit',
        'Thank you, your feedback was sent to us for approval!',
        'Feedbacks',
        'Donations',
        'Want to support the organisation?',
        'You can now donate or leave a positive feedback so we can continue helping other students',
        'Contribute'
    ],
    recommendations: [
        'Our recommendations',
        'Support',
        'Our services',
        'Recommended from Domakin.nl',
        'The team of Domakin.nl has made this list in order to help anyone with finding or lending properties in all of the Netherlands. Here you can find platforms to help with your searching and you can always count on us for support or extra services! Simply click the name to view the platform.',
        'Websites',
        'by Domakin.nl',
        'In case you need more information or any help, please contact us through the contact page or our service page!',
        'Be aware of scammers on Facebook. Share documents only with trusted profiles and always require an in-person meeting or video call. If you are in doubt, better call us for help.'
    ]
    ,
    privacyPolicyContent: [
        "Effective Date: 1st of August 2023",
        "At Domakin, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy outlines how we collect, use, and safeguard your data while you use our platform to find accommodations in the Netherlands. By accessing and using the Domakin website or mobile application (referred to as the \"Platform\"), you consent to the practices described in this Privacy Policy.",
        "1. Information We Collect",
        "We may collect various types of information from you, including but not limited to:",
        "Personal information: Your name, email address, phone number, and other contact details.\nProfile information: Details about your preferences, interests, and accommodation requirements.\nCommunication information: Records of correspondence between you and Domakin.\nUsage information: Data about your interactions with the Platform, such as search queries, viewed listings, and user interactions.",
        "2. How We Use Your Information",
        "We use the collected information for the following purposes:",
        "To facilitate your use of the Platform and provide personalized services.\nTo match you with suitable accommodation listings based on your preferences.\nTo improve our services, user experience, and customer support.\nTo communicate with you about your account, listings, and related updates.\nTo analyze usage patterns and conduct research to enhance our offerings.",
        "3. Sharing of Information",
        "We may share your information in the following circumstances:",
        "With accommodation providers: Your profile information may be shared with accommodation owners to facilitate booking and communication.\nWith third-party service providers: We may engage trusted third parties to assist us in providing services, such as payment processing or data analytics.\nLegal compliance: We may disclose information if required by law or to protect our rights, privacy, safety, or property, or that of others.",
        "4. Your Choices",
        "We employ industry-standard security measures to safeguard your data from unauthorized access, disclosure, alteration, or destruction.",
        "5. Data Security",
        "The Platform is not intended for individuals under the age of 16. We do not knowingly collect personal information from minors without parental consent.",
        "6. Children's Privacy",
        "We may update this Privacy Policy as our practices evolve or legal requirements change. Any changes will be posted on the Platform, and your continued use of the Platform after such changes signifies your acceptance of the updated policy.",
        "7. Changes to Privacy Policy",
        "If you have questions, concerns, or requests related to your privacy, please contact us at [contact email/phone].",
        "Thank you for trusting Domakin with your accommodations search. We are dedicated to ensuring your privacy and providing a secure and user-friendly experience on our platform."
    ]






}

export { BG, EN }