const BG = {
    header: [
        'Начална страница',
        'Предпочитан език',
        'За компанията',
        'Контакти',
        'Записване',
        'Грьонинген, Нидерландия',
        'Услуги',
        'Информация',
        'Екип'
    ],
    footer: [
        'Всички права са собственост на компанията @ Domakin ',
        'Условия & Регулации',
        'Грьонинген, Нидерландия',
        'За компанията',
        "Информация",
        'Екип',
        'Услуги',
        'Oгледи',
        'Очаквайте още скоро...',
        'Помощ',
        'Контакти',
        'Наемане',
        'Прехвърляне',
        'Отзиви',
    ],
    about: [
        "Информация за нас",
        "За компанията",
        'Подпомагане при търсене на жилище',
        'Кога да ни потърсите:',
        'В края на 2022 година част от екипа на Domakin.nl създаде студентската организация с нестопанска цел',
        'с идеята да се подобри животът на българските студенти в Холандия. Част от тази ни наша мисия е свързана и с едно от най-големите предизвикателства на студентите в Холандия, а именно намирането на жилище. Затова ние създадохме Domakin.nl с цел да улесним този процес и да помогнем на повече българи да намерят своя нов дом.',
        'Едно от най-големите премеждия на всеки студент в Нидерландия е намиране на жилище в първата учебна година, а и през следващите. Екипът на Domakin.nl ще Ви помогне: ',
        'Ако сте в България и искате да намерите жилище, но няма как да присъствате на огледи, ние сме тук вместо Вас!',
        'Ако искате да намерите жилище, нашият сайт ще Ви помогне!',
        'Ако си търсите съквартирант или искате да си прехвърлите стария договор на някого, нашият сайт е тук за Вас!',
    ],
    contact: [
        'Свържете се с нас',
        'Контакти',
        'E-поща',
        'Телефон за връзка',
        'Очаквайте скоро',
        'Офис Адрес',
        'Очаквайте скоро',
        'Съобщението е изпратено успешно!',
        'Грешка! Моля опитайте пак!',
        'Свържете се директно с нас',
        'Въведете вашия имейл',
        'Въведете тема на запитване',
        'Въведете вашето запитване',
        'Изпрати запитване'
    ],
    viewing: [
        'Извършване на огледи',
        'Огледи',
        'Ние извършваме огледа вместо Вас',
        'Намерили сте квартира, но нямате възможност да присъствате на оглед или сте в процес на търсене и искате да си осигурите агент за огледи.',
        'Предлагаме услугата агент за огледи, при която ние отиваме на оглед от Ваше име. При желание документираме целия оглед и задаваме въпросите Ви лично на наемодателя. Ако има възможност, можем да направим и видео връзка в реално време, за да се доближим максимално до присъствен оглед. Свържете се с нас, следвайки стъпките по-долу:',
        '1) Попълнете бланката по-долу',
        '2) Изчакайте връзка с наш агент',
        '3) Заедно планирайте оглед/ите и оставете всичко останало на нас',
        'Попълнете информацията си',
        'Име',
        'Фамилия',
        'Телефон за връзка (+ кода на държавата)',
        'Ел. поща',
        'Допълнителна информация, която искате да предадете на агента ни',
        'Давам разрешение компанията да се свърже с мен по телефон или по ел. поща, като разрешавам подадената лична информация да бъде запазена и използване единствено във връзка с предлаганата услуга', 'Разбирам, че ще бъда таксуван за услугата, когато и двете страни изпълнят задълженията си и услугата е извършена успешно',
        'Изпращане',
        {
            errors: [
                "Моля, въведете име",
                "Моля, въведете фамилия",
                'Номерът е непълен или не започва с държавен индекс (например +359)',
                "Моля, въведете телефонен номер",
                "Имейлът е навалиден",
                "Моля, въведете имейл",
                "Условията трябва да бъдат приети"
            ]
        },
        'Успешно свързване',
        'Вашата информация вече е получена и очаква разглеждане от наш агент! Благодарим Ви за доверието - очаквайте връзка!',
    ],
    renting: [
        'Наемане на квартира',
        'Наемане',
        'Намерете подходящата квартира за вас',
        'Нашият сайт предлага различни квартири спрямо различни условия. Разгледайте списъка с различни имоти и кликнете снимката, за да разгледате галерията. При интерес, следвайте стъпките: ',
        `1) Изберете имот от секцията по-долу и кликнете 'Избери'`,
        '2) Попълнете формата, която ще се появи при селектиран имот',
        '3) Изчакайте връзка с наш агент за допълнителна информация за имота',
        '4) Завършете сделката с нашия агент',
        'Услуги',
        'Предлагани имоти',
        'на месец',
        'избери'
    ],
    lending: [
        'Прехвърли стар договор',
        'Прехвърляне',
        'Прехвърлете стария си договор чрез нас',
        'Предлагаме опцията да си прехвълите оставащия договора на намерен от нас клиент. За тази цел, Вашият договор трябва да позволява прехвърляне и съгласие на наемодателя. За да стартирате процедурата, моля изпълнете следни стъпки: ',
        '1) Попълнете бланката по-долу',
        '2) Изчакайте обратна връзка с наш агент',
        '3) Заедно разгледайте договора Ви и завършете сделката',
    ],
    FOR_RENT: [
        {
            id: '0',
            status: 'наемане',
            price: 600,
            type: 'Стая за двама',
            location: 'Visvliet, Netherlands',
            description: ['Стая за двама в споделена къща на 20 км от Гроьнинген. Къщата се държи от възрастна португалска двойка. В цената са включени всички консумативи', 'Споделя се хол, баня и тоалетна', 'Договорът е за 12 месеца', 'Налична от 1ви август'],
            main_image: "assets/img/properties/1.jpg",
            images: ['assets/img/properties/21.jpg', 'assets/img/properties/18.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/4.jpg', 'assets/img/properties/5.jpg', 'assets/img/properties/6.jpg', 'assets/img/properties/8.jpg', 'assets/img/properties/9.jpg', 'assets/img/properties/10.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },
        {
            id: '1',
            status: 'наемане',
            price: 400,
            type: 'Единична стая',
            location: 'Visvliet, Netherlands',
            description: ['Единична стая в споделена къща на 20 км от Грьонинген. Къщата се държи от възрастна португалска двойка. В цената са включени всички консумативи.', 'Споделя се хол, баня и тоалетна', 'Договорът е за 12 месеца', 'Налична от 1ви август'],
            main_image: "assets/img/properties/7.jpg",
            images: ['assets/img/properties/19.jpg', 'assets/img/properties/20.jpg','assets/img/properties/2.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },
    ],
    home: [
        'Компания за подпомагане на намиране на квартири',
        'Намерете Вашето място',
        'с наша помощ',
        'Ние ще Ви помогнем с намиране и отдаване на квартири във всяка част на Холандия',
        'Направете запитване',
    ],
    features: [
        'Услуги',
        'Нашите услуги',
        'Извършване на огледи',
        'Нашите агенти извършват огледите вместо Вас, като спазват в    сички Ваши изисквания',
        'Към услугата',
        'Наемане на квартира',
        'Разгледайте нашите предложения в околността и се свържете с нас, за да получите повече информация',
        'Отдай стая',
        'Услуги',
        'В случай, че търсите съквартирант или искате да прехвърлите на стар договор'
    ],
    team: [
        'Екип',
        'Екип',
        {
            name: 'Лазар Попов',
            position: 'Агент за огледи',
            about: '26, бакалавър по изкуствен интелект',
            aboutExtra: `Здравейте, казвам се Лазар, от Русе, но живея в Грьонинген вече пета година. Аз съм магистър по специалност “Изкуствен интелект”. Познавам града добре и съм запознат с търсенето и намирането на жилища под наем. Моите интереси са бойни спортове и изкуствен интелект, като освен агент в Domakin.nl съм президент и съосновател на студентската non-profit организация Bulgarian Society Groningen. Ще се радвам да Ви бъда от помощ!`
        },
        {
            name: 'Сава Попов',
            position: 'Агент за огледи',
            about: '20,  студент по креативна медиа',
            aboutExtra: 'Здравейте, аз съм Сава и съм студент в специалност “Креативна медиа и технологии” в Грьонинген. Прекарвах голяма част от свободното си време в търсене на апартамент, ходене по огледи и разпитвайки познати. След многобройни неуспешни опити успях да намеря жилище и смятам, че вече добре осъзнавам грешките и успехите си при търсенето на квартири. Ще се радвам да бъда от полза на всеки, изпаднал в моята ситуация!'
        },
        {
            name: 'Константин Сонев',
            position: 'Агент за огледи',
            about: '21,  студент по креативна медиа',
            aboutExtra: `Здравейте, казвам се Константин и уча  специалност “Креативна медиа и технологии” в Грьонинген. В края на миналата учебна година ми се наложи да си търся нова квартира. Беше изключително трудно да се сдобия със стая в града и бях удовлетворен, когато намерих място след многократни, неуспешни опити. Има много затруднения при намирането на квартири заради огромния поток от студенти и високи наеми. Знаем, че много от вас имат желанието да учат в града и срещат същите затруднения, най-вече когато не са в града. Поради тази причина ние от Domakin.nl искаме да помогнем, предоставяйки нашите услуги. Очаквам да работим заедно!`
        },
        {
            name: 'Димитър Стаматов',
            position: 'Агент за огледи',
            about: '22, студент по международен бизнес',
            aboutExtra: 'Здравейте, казвам се Димитър Стаматов, на 22 години и съм студент трета година в Холандия. Уча бизнес и работя като барман, а в свободното си време тренирам бойни спортове и се занимавам с музика. Като всеки студент в Холандия знам колко е трудно намирането на жилище особено през първата година и затова бих се радвал да улесня всеки бъдещ студент с работата ми като агент в Domakin.nl.'
        },
        {
            name: 'Владислав Маринов',
            position: 'IT Мениджър',
            about: '22, International Business student',
            aboutExtra: 'Здравейте, казвам се Владислав и съм студент по бизнес в Лондон, Англия. Макар и в друга държава, аз също съм запознат с проблемите, които един студент може да срещне с търсенето на жилище. Стрес, отчаяние и ярост са само няколко емоции, които лично аз съм изпитвал при търсенето на квартира в Лондон и знам какви трудности може да изпита човек, особено когато търси дистанционно. За мен е удоволствие да работя по тази платформа, която вярвам, че ще помогне на мнозина!'
        },
        {
            name: 'Радост Лозанова',
            position: 'Дизайн Мениджър',
            about: '22, International Business student',
            aboutExtra: `Здравейте! Аз съм Радост, креативен директор и съосновател на Bulgarian Society Groningen. Като студентка съм живяла в доста държави, което е съпроводено с често местене. Като част от екипа на Domakin.nl, ще се радвам да помогна на повече българи да намерят своя нов дом в Холандия.`
        },
        'Агенти',
        'Маркетинг',
        'Дизайн',
    ],
    error: [
        'Внимание, попаднахте на грешка!',
        'Страницата не е намерена',
        'Страницата, която търсехте, не съществува! Възможно е да е преместена или изтрита.',
        ' Обратно към начало',
    ],
    feedbacks : [
        'Остави отзив',
        'За нас',
        'Отзиви',
        'Сподели Вашето впечатление от услугите ни',
        'Име',
        'Вашият отзив',
        'Минимум 20 символа',
        'Изпрати',
        'Името е задължително',
        'Не оставяйте отзива празен',
        'Минимум 20 символа са нужни',
        'Надвишихте лимита от 300 думи',
        'Благодарим, очаквайте отзива ви да бъде одобрен съвсем скоро!'
    ]
}

const EN = {
    header: [
        'Home',
        'Change language',
        'About',
        'Contact',
        'Register',
        'Groningen, the Netherlands',
        'Services',
        'Information',
        'Agents'
    ],
    footer: [
        'All Rights Reserved @ Domakin ',
        'Terms & Policy',
        'Groningen, the Netherlands',
        'Company',
        "About us",
        'Team',
        'Services',
        'Viewings',
        'Expect more soon...',
        'Support',
        'Contact us',
        'Renting',
        'Lending',
        'Feedbacks'
    ],
    about: [
        "About the company",
        "About us",
        'Helping you find a place',
        'When to reach us:',
        'At the end of 2022 some of the founders of Domakin started the NPO',
        'with the aim to help the Bulgarian students of Groningen. Part of our mission includes one of the biggest challenges of students in Groningen - finding an accommodation. That is why we created Domakin in order to make this process easier for many that find difficulties in finding a place to live.',
        'It is hard for a student to find a place to live in their first year and even in the rest. The team of Domakin will help you with: ',
        'If you are located in Bulgaria and want to find a place but you are unable to make the viewing, we are here for you!',
        'If you want to find a place, we are here for you!',
        'If you are searching for a new flatmate or want to transfer your contract to someone else, we are here for you!',
    ],
    contact: [
        'Contact us',
        'Contact',
        'E-mail',
        'Telephone',
        'Expect soon',
        'Office Address',
        'Expect soon',
        'Your message was sent successfully',
        'Error! Please try again!',
        'Contact us directly',
        'Enter your email',
        'Enter the subject',
        'Enter you message',
        'Send'
    ],
    viewing: [
        'Viewing service',
        'Viewing',
        'Let us make the viewing for you',
        'You have found a room/apartment but you are unable to attend the viewing or you are in the process of searching and want to ensure that someone can represent you for the viewing.',
        'We offer agents for viewings where we go to the viewing instead of you. By your request we document the whole process and make any inqueries to the landlord. If there is a possibility, we can make a live connection with you so you can realisticaly experience the viewing. Contact us by following the steps below: ',
        '1) Fill your details in the form',
        '2) Wait for one of our agents to contact you',
        '3) Arrange the viewing/s and leave the rest to us',
        'Fill your details',
        'Name',
        'Surname',
        'Phone to be contacted (+ and country code)',
        'Email',
        'Any comments you would like to be sent to our agent',
        'I give my consent to be contacted by the company via phone or email and for them to store my information for service purposes only',
        'Submit Request',
        {
            errors: [
                "Name is required",
                "Surname is required",
                'Phone number is not full or does not start with country code (example +359)',
                "Phone is required",
                "Please enter a valid email",
                "Please enter an email",
                "Terms must be accepted"
            ]
        },
        'Successful Request',
        'Your information has been sent so expect soon to be contacted by one of our agents! Thank you again for the trust and see you soon!',
    ],
    renting: [
        'Renting accommodations',
        'Renting',
        'Find the perfect place for you',
        'Our platform contains different properties.',
        `1) Choose a property from the list below and click 'Select'`,
        '2) Fill the form that will appear once a property has been selected',
        '3) Wait to be contacted by our agent to finilize the deal',
        '4) Finish the deal with our agent',
        'Services',
        'Properties',
        'per month',
        'select'
    ],
    lending: [
        'Transfer and old contract',
        'Transfering',
        'Transfer your old contract through us',
        'We offer you to transfer the remain of your contract to one of our clients. In order to achieve this, your contract should allow for such execution and your landlord should be informed. To start, simply follow the steps below: ',
        '1) Fill the form',
        '2) Wait for our agent to contact you',
        '3) Together check the contract and finilize the service',
    ],
    FOR_RENT: [
        {
            id: '0',
            status: 'rent',
            price: 600,
            type: 'Double Room',
            location: 'Visvliet, Netherlands',
            description: ['Room for two in a shared house just 20km from Groningen. The house is owned by a Portogues couple. Price includes all bills', 'Contract is for 12 months', 'Available from 1st of August'],
            main_image: "assets/img/properties/1.jpg",
            images: ['assets/img/properties/21.jpg', 'assets/img/properties/18.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/4.jpg', 'assets/img/properties/5.jpg', 'assets/img/properties/6.jpg', 'assets/img/properties/8.jpg', 'assets/img/properties/9.jpg', 'assets/img/properties/10.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },
        {
            id: '1',
            status: 'rent',
            price: 400,
            type: 'Single Room',
            location: 'Visvliet, Netherlands',
            description: ['Room for one in a shared house just 20km from Groningen. The house is owned by a Portogues couple. Price includes all bills', 'Contract is for 12 months', 'Available from 1st of August'],
            main_image: "assets/img/properties/7.jpg",
            images: ['assets/img/properties/19.jpg', 'assets/img/properties/20.jpg','assets/img/properties/2.jpg', 'assets/img/properties/3.jpg', 'assets/img/properties/14.jpg', 'assets/img/properties/15.jpg', 'assets/img/properties/16.jpg', 'assets/img/properties/11.jpg', 'assets/img/properties/12.jpg', 'assets/img/properties/13.jpg'],
        },

    ],
    home: [
        'Company for accommodation searching',
        'Find your place to live',
        'with our help',
        'Our young team will help you find a place to live in any part of the Netherlands',
        'Contact us',
    ],
    features: [
        'Our Main Focus',
        'Our Services',
        'Viewings',
        `Our agents make the apartment visits for you by also following any client's requirements`,
        'Check it out',
        'Rent an apartment',
        'Check the properties on our site and make an inquery for more information',
        'List a room',
        'Services',
        'Search for a new flatmate / Transfer your contract'
    ],
    team: [
        'Team',
        'Propert Agents',
        {
            name: 'Lazar Popov',
            position: 'Viewing Agent',
            about: '26, Bachelor in Artificial Intelligence',
            aboutExtra: `Hello, my name is Lazar. I'm from Ruse, but I have been living in Groningen for five years now. I have a master's degree in "Artificial Intelligence". I am familiar with the city and have experience in searching for and finding rental properties. My interests include combat sports and artificial intelligence. Besides being an agent at Domakin.nl, I am also the president and co-founder of the non-profit student organization Bulgarian Society Groningen. I would be happy to assist you!`
        },
        {
            name: 'Sava Popov',
            position: 'Viewing Agent',
            about: '20, Creative Media student',
            aboutExtra: `Hello, I'm Sava and I'm a student in the "Creative Media and Technologies" program in Groningen. I have spent a lot of my summer time before coming to this town in searching for apartments, going on viewings, and asking acquaintances for advice. After numerous unsuccessful attempts, I finally managed to find a place, and I believe I now have a good understanding of the mistakes and successes in apartment hunting. I would be glad to help anyone who is in a similar situation!`
        },
        {
            name: 'Konstantin Sonev',
            position: 'Viewing Agent',
            about: '21, Creative Media student',
            aboutExtra: `Hello, my name is Konstantin, and I study "Creative Media and Technologies" in Groningen. At the end of the previous academic year, I had to search for a new apartment. It was extremely difficult to find a room in the city, and I was satisfied when I finally found a place after multiple unsuccessful attempts. There are many difficulties in finding apartments due to the high influx of students and high rents. We know that many of you have the desire to study in the city and face the same difficulties, especially when you are not in the city. That's why we at Domakin.nl want to help by providing our services. I look forward to working together!`
        },
        {
            name: 'Dimitar Stamatov',
            position: 'Viewing Agent',
            about: '22, International Business student',
            aboutExtra: `Hello, my name is Dimitar Stamatov, I'm 22 years old, and I'm a third-year student in the Netherlands. I study business and work as a bartender, and in my free time, I train in combat sports and engage in music. Like every student in the Netherlands, I know how difficult it is to find accommodation, especially in the first year. That's why I would be happy to assist any future student with my work as an agent at Domakin.nl.`
        },
        {
            name: 'Vladislav Marinov',
            position: 'IT Manager',
            about: '22, International Business student',
            aboutExtra: ` Hello, my name is Vladislav, and I'm a business student in London, England. Although in a different country, I am also familiar with the problems a student can encounter when searching for accommodation. Stress, despair, and anger are just a few emotions I have experienced personally while looking for an apartment in London, and I know the difficulties one can face, especially when searching remotely. It is a pleasure for me to work on this platform, which I believe will help many people!`
        },
        {
            name: 'Radost Lozanova',
            position: 'Design Manager',
            about: '22, International Business student',
            aboutExtra: `Hello! I'm Radost, a creative director and co-founder of Bulgarian Society Groningen. As a student, I have lived in several countries, which involved frequent moving. As part of the Domakin.nl team, I would be happy to help more Bulgarians find their new home in the Netherlands.`
        },
        'Agents',
        'Marketing',
        'Design',
    ],
    error: [
        'Be careful - You just got an error!',
        'Page not found',
        'The page you are looking for does not exists',
        ' Back to home',
    ],
    feedbacks : [
        'Leave feedback',
        'About',
        'Feedbacks',
        'Share your experience for others to see',
        'Name',
        'Your Feedback',
        'Minimum 20 characters',
        'Send',
        'Name is required',
        'Do not leave empty',
        'Please type at least 20 characters',
        'You passed the 300 characters limit',
        'Thank you, your feedback was sent to us for approval!'
    ]
}

export { BG, EN }